### ISSUE TITLE
InodesMonitoring.php

### ISSUE THREAD

**Issue by maelandipadapa** [fauguste/cloudwatch-script-php#3]
<?php
namespace CloudWatchScript\Plugins;

use CloudWatchScript\AbstractMonitoring;

/**
 * Check Solr using ping URL.
 * Add and configure the following lines to the config file
 * "Inodes" : {
 *         "name" : "Name of metric and alarm",
 *         "maxUsed": 90,
 *         "namespace": "Metric/Namespace",
 *         "description": "Description"
 * }
 */
class InodesMonitoring extends AbstractMonitoring
{
    private $maxUsed;

    /**
     * @param array $config
     * @param String $name
     */
    public function __construct($config, $name)
    {
        parent::__construct($config, $name);
        $this->maxUsed = $this->config->maxUsed;
    }

    /**
     * @return integer Percentage of use memory
     */
    public function getMetric()
    {
        $percent = exec("df / -i | grep \'/$\' | grep '..%' -o");
        return (int)$percent;
    }

    /**
     * @return string "None"
     */
    public function getUnit()
    {
        return "Percent";
    }

    /**
     * @return array Alarm max for memory used
     */
    public function getAlarms()
    {
        return array(
                array("ComparisonOperator" => "GreaterThanThreshold",
                        "Threshold" => $this->maxUsed,
                        "Name" => $this->name . " exceed " . $this->config->maxUsed . " %")
        );
      }
  }

**Comment by fauguste** [comment]
Please, Could you create a pull request with your code ?

Thanks.

**Comment by maelandipadapa** [comment]
I don't have access permission on the repo so I can't push my branch. My
github account is
*maelandipadapa*

Cheers

**Comment by fauguste** [comment]
1) Fork project in your account.
2) Apply modification
3) Create a pull request.
